smarts:
  # Environment
  sumo_gui: False # If True, enables sumo-gui display.
  img_meters: 50 # Observation image area size in meters.
  img_pixels: 112 # Observation image size in pixels.
  num_stack: 3 # Number of frames to stack as input to policy network.
  # scenarios: 
  #   - "1_to_2lane_left_turn_c"
  #   - "1_to_2lane_left_turn_t"
  #   - "3lane_merge_single_agent"
  #   - "3lane_cruise_single_agent"
  #   - "3lane_overtake"
  
  # scenarios: 
  #   - "3lane_cruise_single_agent"
  #   - "3lane_overtake"
  #   - "3lane_cut_in"
  #   - "3lane_merge_single_agent"
  #   - "1_to_2lane_left_turn_c"
  #   - "1_to_2lane_left_turn_t"

  scenarios: 
    - "3lane_cruise_single_agent"
    - "3lane_overtake"
    - "3lane_merge_single_agent"
    - "1_to_2lane_left_turn_c"
    - "1_to_2lane_left_turn_t"
    - "3lane_cut_in"
    

    # - "1_to_3lane_left_turn_t_rotated_agents_1"
    # - "1_to_3lane_left_turn_middle_lane_c_agents_1"
    # - "1_to_3lane_left_turn_c_rotated_agents_1"
    # - "1_to_3lane_left_turn_upside_c_agents_1"
    # - "1_to_3lane_left_turn_upside_c_rotated_agents_1"
    # - "1_to_3lane_left_turn_t_rotated_agents_1"

    # - "1_to_3lane_right_turn_c_agents_1"
    # - "1_to_3lane_right_turn_c_rotated_agents_1"
    
    # - "3lane_shoulder_agents_1"
    # - "2lane_shoulder_agents_1"
    # - "2lane_agents_1"
    # - "2lane_shoulder_short_agents_1"
    # - "3lane_curve_agents_1"
    # - "3lane_shoulder_short_agents_1"
    # - "4lane_agents_1"
    # - "2lane_shoulder_short_agents_1"
    # - "2lane_slow_agents_1"
    # - "3lane_curve_slow_agents_1"
    # - "4lane_slow_agents_1"

